format = """
[](bright-white)\
[  ](fg:black bg:bright-white)\
[](bg:blue fg:bright-white)\
$directory\
[](fg:blue bg:green)\
$git_branch\
$git_status\
[](fg:green)\
$fill\
[](fg:red)\
$username\
[ ](fg:yellow bg:red)\
$hostname\
[](fg:bright-white bg:yellow)\
$time\
[](fg:bright-white)\
\n$character"""

[fill]
symbol = '-'
style = 'fg:bright-black'

[character]
success_symbol = '[ ](bold green)'
error_symbol = '[ ](bold red)'

[directory]
style = "fg:black bg:blue"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "󰉒 /"
home_symbol = " "
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:#090c0c bg:#A3BE8C)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:#090c0c bg:#A3BE8C)]($style)'

[time]
disabled = false
time_format = "%R"
format = '[[  $time ](fg:black bg:bright-white)]($style)'

[hostname]
ssh_only = true
format = '[󰌘 ](fg:black bg:yellow)[$ssh_symbol](fg:black bg:yellow)'
trim_at = ''
disabled = false

[username]
style_user = "bg:red fg:black"
format = '[ ]($style)[$user]($style)'
disabled = false
show_always = true
