#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
(cd $CONFIG_DIR/helper && make)
$CONFIG_DIR/helper/helper $HELPER > /dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
  height=27
  color=$BAR_COLOR
  border_width=1
  border_color=$SHADOW
  shadow=off
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  topmost=window
  margin=-1
  y_offset=-1
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:11.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:11.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=20
  background.corner_radius=6
  background.border_width=1
  popup.background.border_width=2
  popup.background.corner_radius=6
  popup.background.border_color=$GREY0
  popup.background.color=$GREY0
  popup.blur_radius=20
  popup.y_offset=5
  popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}"

# left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/yabai.sh"
source "$ITEM_DIR/front_app.sh"

# center
source "$ITEM_DIR/calendar.sh"

# right
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/wifi.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded"
